# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java#apache-maven-with-a-settings-path

name: Maven Package

on:
  release:
    types: [created]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Maven release
      uses: qcastel/github-actions-maven-release@v1.0.3
      with:
    # Filter the branch to execute the release on
       release-branch-name: master # optional
    # Enable gpg signing
       gpg-enabled: true # optional
    # The GPG key ID
       gpg-key-id: 18700AB8 # optional
    # The GPG key
       gpg-key: ${{secrets.PGP_PRI_KEY}} # optional
    # The maven local repository path
    # Maven server repository id to push the artefacts to
       maven-repo-server-id: ${{secrets.SERVER_ID}}
    # Maven server repository username
       maven-repo-server-username: ${{secrets.SERVER_USERNAME}}
    # Maven server repository password
       maven-repo-server-password: ${{secrets.SERVER_PASSWORD}}
    # The maven arguments for the releas
    - name: eee
      run: mvn clean -DskipTests=true deploy
