# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java#apache-maven-with-a-settings-path

name: Maven Package

on:
  release:
    types: [created]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
        server-id: ${{secrets.SERVER_ID}} # Value of the distributionManagement/repository/id field of the pom.xml
        server-username: ${{secrets.SERVER_USERNAME}} # location for the settings.xml file
        server-password: ${{secrets.SERVER_PASSWORD}}
        gpg-private-key: ${{secrets.PGP_PRI_KEY}}
    - name: Build with Maven
      run: mvn clean deploy
